### Installing NumPy
Setting up the numerical computing library in the environment.


In [1]:
## Numpy

!pip install numpy

### Creating 1D Arrays
Basics of array creation, checking type, and inspection of shape.


In [3]:
import numpy as np 

## create array using numpy
## create a 1D array

arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


### Reshaping Arrays
Changing the dimensions of an array without changing its data.


In [5]:
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5) ##this means 1 row and 5 columns

array([[1, 2, 3, 4, 5]])

### Array Inspection
Checking the shape of multi-dimensional arrays.


In [9]:
arr2=np.array([[1,2,3,4,5,6]])
arr2.shape

(1, 6)

### Creating 2D Arrays
Defining matrices with rows and columns.


In [13]:
## 2d array

arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


### Generating Ranges
Using np.arange() to create sequences of numbers.


In [17]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

### Combining Ranges and Reshaping


In [18]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

### Utility Arrays
Creating arrays filled with ones, zeros, etc.


In [22]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### Core Array Attributes
Understanding ndim, size, dtype, and itemsize.


In [23]:
## Attributes

arr=np.array([[1,2,3],[4,5,6]])

print("Array:\n",arr)
print("Shape:",arr.shape) ## O/P : (2,3)
print("Number of dimensions:",arr.ndim) ## O/P : 2
print("Size(number of elements):",arr.size) ## O/P : 6
print("Data type:",arr.dtype) ## O/P int64(may vary based on platform)
print("Item Size (in bytes):",arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size(number of elements): 6
Data type: int64
Item Size (in bytes): 8


### Vectorized Operations
Performing element-wise arithmetic across arrays efficiently.


In [27]:
## Numpy Vectorized Operation

arr1=np.array([1,2,3,4,5])
arr1=np.array([10,20,30,40,50])

#Element vise addition
print("Addition:",arr1+arr2)

##Element vise substartion
print("Substartion:",arr1 - arr2)


##Element vise Multiply
print("Multiply:", arr1 * arr2)


##Element vise Division
print("Division:", arr1 / arr2)

Addition: [[11 22 33 44 55]
 [12 23 34 45 56]]
Substartion: [[ 9 18 27 36 45]
 [ 8 17 26 35 44]]
Multiply: [[ 10  40  90 160 250]
 [ 20  60 120 200 300]]
Division: [[10.         10.         10.         10.         10.        ]
 [ 5.          6.66666667  7.5         8.          8.33333333]]


### Universal Functions (ufuncs)
Applying mathematical operations like sqrt, exp, and log to whole arrays.


In [29]:
##Universal Function
arr=np.array([2,3,4,5,6])

##square root
print(np.sqrt(arr))

##Exponential
print(np.exp(arr))

##Sine 
print(np.sin(arr))

##natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


### Indexing and Slicing Basics
Accessing specific elements and sub-regions of multi-dimensional arrays.


In [5]:
## Array slicing and indexing 
import numpy as np 

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array : \n", arr)

Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### Row Selection


In [11]:
 arr[0]

array([1, 2, 3, 4])

### Specific Element Access


In [12]:
arr[0][2]

np.int64(3)

### 2D Slicing Examples


In [21]:
print(arr[0][0])
print(arr[0:2,2:])

1
[[3 4]
 [7 8]]


### Advanced Slicing


In [18]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

### Column-wise Slicing


In [22]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


### Modifying Array Content
Updating specific elements using indexing.


In [23]:
## Modify array elemnts

arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


### Block Modification
Updating entire rows or regions at once.


In [25]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


### Statistical Normalization
Scaling data to have a mean of 0 and a standard deviation of 1.


In [26]:
### Statistical concepts --Normaliszation
## to have a mean of 0 and standard deviation of 1

data =np.array([1,2,3,4,5])

# Calculate the mean and standard deviation
mean = np.mean(data)
std_dev=np.std(data)

#Normalize the data
normalized_data=(data-mean)/std_dev
print("Normalized data:",normalized_data)

Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


### Summary Statistics
Calculating mean, median, std, and var using NumPy functions.


In [27]:
data =np.array([1,2,3,4,5,6,7,8,9,10])

##Mean
mean=np.mean(data)
print("Mean:",mean)

# Median
median = np.median(data)
print("Median:",median)

#Standrad Deviation
std_dev = np.std(data)
print("Standard Deviation:",std_dev)

#variance
variance = np.var(data)
print("Varience:",variance)

Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Varience: 8.25


### Conditional Selection
Filtering array elements based on logical conditions (Boolean Indexing).


In [32]:
##Logical operation

data=np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>5) & (data<=8)]

array([6, 7, 8])